Publish release
libsql/sqld pull request #474
Opened 2023-06-14 21:07 UTC by dyasny

Now that we have an arm64 mac runner, adding the code to utilize it in release builds.

2023-06-15 14:52 UTC, MarinPostma requested changes

2023-06-15 14:52 UTC, MarinPostma commented on .github/workflows/publish.yml
> +          brew install pkg-config<<<<<<< publish-release
merge conflict?
```suggestion
          brew install pkg-config
```

2023-06-19 13:03 UTC, dyasny commented
I also removed the on.push.["main"] bit, now it will only publish when a new v.*.*.* tag is created

2023-06-20 18:25 UTC, MarinPostma approved these changes

2023-06-20 18:37 UTC, merged