Introduce initial-idle-shutdown-timeout-s
libsql/sqld pull request #528
Opened 2023-07-13 12:47 UTC by haaawk

This new parameter makes it possible to define different
idle shutdown timeout for instance that has been started
but never received any requests.

It is useful for maintainance operations like periodic syncing
replica with the primary even when the replica does not serve
any requests at the moment. The assumption is that such maintainance
operation could wake up the replica for much shorter time than
idle-shutdown-timeout used after receiving actual user request.

2023-07-13 13:23 UTC, MarinPostma requested changes

2023-07-13 13:23 UTC, MarinPostma commented on sqld/src/main.rs
> +    #[clap(long, env = "SQLD_INITIAL_IDLE_SHUinitialTDOWN_TIMEOUT_S")]
```suggestion
    #[clap(long, env = "SQLD_INITIAL_IDLE_SHUTDOWN_TIMEOUT_S")]
```

2023-07-13 13:23 UTC, MarinPostma commented
otherwise LGTM

2023-07-14 10:13 UTC, haaawk commented on sqld/src/main.rs
> +    #[clap(long, env = "SQLD_INITIAL_IDLE_SHUinitialTDOWN_TIMEOUT_S")]
Thanks for catching this.

2023-07-14 11:48 UTC, MarinPostma approved these changes

2023-07-14 12:02 UTC, merged