wal file improvements
libsql/sqld pull request #72
Opened 2023-01-20 16:19 UTC by MarinPostma

this PR introduces some overall improvements to our custom WAL file format.

- The WAL file header is improved to contain more informartion:
    - the database UUID that the log is replicating
    - Fields like initial checksum, start_frame_index for log compaction
    - a magic number
- Each WAL frame is now preceded by a `WalFrameHeader`, that contains:
    - The running checksum of the pages, including the current page.
    - The id of the start_frame_index
    - the page_no of the of the page contained in the frame
    - size_after: 0 on non-commit frame, otherwise, equal to the size (in page), of the database after applying those frames. (passed to and from the `xFrame` call).

2023-02-02 10:46 UTC, psarna commented
It's been a while since I last looked at the wal_logger impl, so first of all I need a step back and some clarification. The new format introduced in this PR makes our own WAL log look more and more like the regular `-wal` file that libSQL produces and stores anyway. Can't we just reuse and replicate that? Is there any information that libSQL WAL journal file misses and our WAL logger has?

Ref: https://www.sqlite.org/fileformat.html#wal_file_format . WAL page header definitely has some fields that we don't need, but it's still just 24 bytes total, so rather meaningless.

2023-02-02 11:28 UTC, MarinPostma commented
It's very similar indeed, I took inspiration from it. There are some slight differences, though, like the fact that our WAL header stores the database ID. Are you suggesting that:
- we use the existing WAL? I'm not a fan, we'd need to deal with checkpointing, and we can't easily evolve the format to suit our need
- Replicate the format, and keep writing in our own WAL? we end up implementing stuff that we don't need, + plus problems from the first point

2023-02-02 12:35 UTC, psarna commented
> It's very similar indeed, I took inspiration from it. There are some slight differences, though, like the fact that our WAL header stores the database ID. Are you suggesting that:
> 
> * we use the existing WAL? I'm not a fan, we'd need to deal with checkpointing, and we can't easily evolve the format to suit our need

Yes, that was my suggestion. Litestream, for instance, does some nifty hacks with checkpointing (https://litestream.io/how-it-works/#the-shadow-wal), but we don't have to, specifically because we fully control checkpoints, from inside `xCheckpoint`. I already leveraged this in bottomless, preventing partial checkpoints and upgrading them all to full checkpoints.

I think we should still consider this, because if we reuse the original WAL, we get the magic numbers, checksums and commit boundaries for free. We also avoid 2x space amplification by keeping everything both in the original WAL and our WAL.

Can you elaborate on "evolve the format to suit our need"? If we expect to need to store some additional information in the near future, then we should indeed consider our own format, but in general we can always offload this future additional information to a separate file, which maps offsets to this special data.

A huge advantage of reusing the WAL is that we stay fully format-compatible with SQLite, can use all the tooling there is to browse the files, checkpoint them, etc. Even litestream would start working out-of-the-box for us, wouldn't it? Since it would properly store both the main file and WAL, and be able to restore everything. So would bottomless, which already simply piggy-backs on the existing WAL file, without creating any external files.

/cc @haaawk

2023-02-02 13:59 UTC, MarinPostma commented
@psarna makes sense, let me give it a good thought

2023-02-10 15:24 UTC, haaawk requested changes
I don't think we should merge this before we fix the replication. Unless we have a way to upgrade existing clusters to the newer version that includes changes from this PR.

2023-02-10 15:36 UTC, haaawk commented
I think what's needed here is the ability to read both old and new format and doing the migration from old format to the new if necessary. Then in a future version we could drop support for reading old format and doing the migration.

2023-02-13 11:27 UTC, MarinPostma commented
bors merge

2023-02-13 11:59 UTC, merged