hrana: add diagnostics for connections
libsql/sqld pull request #729
Opened 2023-10-04 09:00 UTC by psarna

This commit adds a `/v2/diagnostics` endpoint which prints various information about current hrana-over-http connections.

Draft, because the diagnostics are currently in a very debuggy format, and I'm figuring out if we can make it more human-readable. Still, they're enough to determine if something is holding a lock via an abandoned hrana-over-http stream.

Example:
```
$ curl -s http://localhost:8080/v2/diagnostics | jq
[
  "Some(TxnSlot { conn: Mutex { data: <locked> }, timeout_at: Instant { tv_sec: 9751, tv_nsec: 546908348 }, is_stolen: false })"
]
$ curl -s http://localhost:8080/v2/diagnostics | jq
[
  "expired"
]

2023-10-04 14:58 UTC, MarinPostma requested changes
One small thing, otherwise LGTM.

We should go over that in the future and design a way to have diagnostic probes that don't couple unrelated modules too much

2023-10-04 14:58 UTC, MarinPostma commented on sqld/src/http/admin/mod.rs
> +        .unwrap())
```suggestion
) -> crate::Result<Json<Vec<String>>> {
    use crate::connection::Connection;
    use hrana::http::stream;

    let server = app_state.user_http_server.as_ref();
    let stream_state = server.stream_state().lock();
    let handles = stream_state.handles();
    let mut diagnostics: Vec<String> = Vec::with_capacity(handles.len());
    for handle in handles.values() {
        let handle_info: String = match handle {
            stream::Handle::Available(stream) => match &stream.db {
                Some(db) => db.diagnostics(),
                None => "[BUG] available-but-closed".into(),
            },
            stream::Handle::Acquired => "acquired".into(),
            stream::Handle::Expired => "expired".into(),
        };
        diagnostics.push(handle_info);
    }
    drop(stream_state);

    tracing::trace!("diagnostics: {diagnostics:?}");
    Ok(diagnostics)
```

2023-10-04 19:03 UTC, MarinPostma commented
@psarna, can you rebase maybe?

2023-10-05 08:21 UTC, psarna commented
This PR should have absolutely 0 to do with with bottomless, and yet I see bottomless test failures, that always pass for me locally. Maybe we have some kind of regression, let me investigate

2023-10-05 08:22 UTC, psarna commented
Oh wait, now they failed for me locally too, good

2023-10-05 09:07 UTC, psarna commented on sqld/src/replication/primary/logger.rs
> +                    return SQLITE_OK;
oh wow, that's leftovers from my early tests, it should *not* be there at all

2023-10-05 09:30 UTC, merged